
(node:466346) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.41',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 18:37:14.988 - [Info] MITM Version: 2
2022-10-25 18:37:14.991 - [Info] Auto Access Enabled: true
2022-10-25 18:37:14.992 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 18:37:15.000 - [Info] SSH man-in-the-middle server for 10.0.3.41 listening on 10.0.3.1:1000
2022-10-25 18:38:13.533 - [Debug] [Connection] Attacker connected: 5.28.139.161 | Client Identification: SSH-2.0-Go
(node:480765) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.85',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 18:38:13.988 - [Info] MITM Version: 2
2022-10-25 18:38:13.991 - [Info] Auto Access Enabled: true
2022-10-25 18:38:13.992 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 18:38:14.002 - [Debug] listen EADDRINUSE: address already in use 10.0.3.1:1000
2022-10-25 18:38:14.012 - [Error] Another MITM instance or another program is already listening on this port
{"level":"error","message":"Forever detected script exited with code: 1"}
2022-10-25 18:38:14.175 - [Debug] [Connection] Attacker connected: 219.140.162.82 | Client Identification: SSH-2.0-Go
2022-10-25 18:38:14.604 - [Debug] [Auth] Attacker 5.28.139.161 trying to authenticate with 'none'
2022-10-25 18:38:14.605 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 18:38:14.952 - [Debug] [Auth] Attacker 5.28.139.161 trying to authenticate with 'publickey'
2022-10-25 18:38:14.953 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 18:38:14.954 - [Debug] [Auth] Attacker: 5.28.139.161 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 18:38:15.310 - [Debug] [Connection] Attacker closed the connection
2022-10-25 18:38:15.437 - [Debug] [Connection] Attacker connected: 117.80.212.33 | Client Identification: SSH-2.0-Go
2022-10-25 18:38:15.470 - [Debug] [Connection] Attacker connected: 5.28.139.161 | Client Identification: SSH-2.0-Go
