
(node:939431) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.175',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:30:15.574 - [Info] MITM Version: 2
2022-10-25 19:30:15.577 - [Info] Auto Access Enabled: true
2022-10-25 19:30:15.577 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:30:15.584 - [Info] SSH man-in-the-middle server for 10.0.3.175 listening on 10.0.3.1:1000
(node:941400) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.227',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:30:47.901 - [Info] MITM Version: 2
2022-10-25 19:30:47.902 - [Info] Auto Access Enabled: true
2022-10-25 19:30:47.903 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:30:47.913 - [Debug] listen EADDRINUSE: address already in use 10.0.3.1:1000
2022-10-25 19:30:47.913 - [Error] Another MITM instance or another program is already listening on this port
{"level":"error","message":"Forever detected script exited with code: 1"}
2022-10-25 19:30:48.961 - [Debug] [Connection] Attacker connected: 36.112.171.51 | Client Identification: SSH-2.0-libssh2_1.8.2
2022-10-25 19:30:49.004 - [Debug] [Connection] Attacker connected: 58.216.8.121 | Client Identification: SSH-2.0-Go
2022-10-25 19:30:49.007 - [Debug] [Connection] Attacker connected: 219.140.162.82 | Client Identification: SSH-2.0-Go
2022-10-25 19:30:49.209 - [Debug] [Connection] Attacker connected: 85.105.82.39 | Client Identification: SSH-2.0-Go
2022-10-25 19:30:50.098 - [Debug] [Auth] Attacker 85.105.82.39 trying to authenticate with 'none'
2022-10-25 19:30:50.098 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:30:50.154 - [Debug] [Connection] Attacker connected: 195.87.73.176 | Client Identification: SSH-2.0-Go
2022-10-25 19:30:50.301 - [Debug] [Connection] Attacker connected: 120.224.143.251 | Client Identification: SSH-2.0-Go
2022-10-25 19:30:50.307 - [Debug] [Auth] Attacker 58.216.8.121 trying to authenticate with 'none'
2022-10-25 19:30:50.307 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:30:50.378 - [Debug] [Auth] Attacker 36.112.171.51 trying to authenticate with 'password'
2022-10-25 19:30:50.381 - [Debug] [Auto Access] Attacker: 36.112.171.51, Threshold: 1, Attempts: 1
2022-10-25 19:30:50.381 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 19:30:50.382 - [Debug] [Auto Access] Adding the following credentials: 'root:root'
2022-10-25 19:30:50.709 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 19:30:50.711 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 19:30:50.711 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.175
2022-10-25 19:30:50.714 - [Debug] [Auth] Attacker 85.105.82.39 trying to authenticate with 'publickey'
2022-10-25 19:30:50.715 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:30:50.716 - [Debug] [Auth] Attacker: 85.105.82.39 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 19:30:50.766 - [Debug] [Auth] Attacker 58.216.8.121 trying to authenticate with 'publickey'
2022-10-25 19:30:50.768 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:30:50.769 - [Debug] [Auth] Attacker: 58.216.8.121 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 19:30:50.839 - [Debug] [Connection] Attacker connected: 191.242.188.103 | Client Identification: SSH-2.0-Go
2022-10-25 19:30:50.996 - [Debug] [Connection] Attacker closed the connection
