
(node:160881) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.79',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 04:33:23.235 - [Info] MITM Version: 2
2022-10-25 04:33:23.236 - [Info] Auto Access Enabled: true
2022-10-25 04:33:23.250 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 04:33:23.263 - [Info] SSH man-in-the-middle server for 10.0.3.79 listening on 10.0.3.1:1000
2022-10-25 04:34:08.620 - [Debug] [Connection] Attacker connected: 31.14.115.42 | Client Identification: SSH-2.0-Go
(node:169755) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.170',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 04:34:09.125 - [Info] MITM Version: 2
2022-10-25 04:34:09.127 - [Info] Auto Access Enabled: true
2022-10-25 04:34:09.128 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 04:34:09.140 - [Debug] listen EADDRINUSE: address already in use 10.0.3.1:1000
2022-10-25 04:34:09.140 - [Error] Another MITM instance or another program is already listening on this port
{"level":"error","message":"Forever detected script exited with code: 1"}
2022-10-25 04:34:09.792 - [Debug] [Auth] Attacker 31.14.115.42 trying to authenticate with 'none'
2022-10-25 04:34:09.793 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 04:34:10.273 - [Debug] [Connection] Attacker connected: 223.171.91.158 | Client Identification: SSH-2.0-Go
2022-10-25 04:34:10.392 - [Debug] [Auth] Attacker 31.14.115.42 trying to authenticate with 'password'
2022-10-25 04:34:10.393 - [Debug] [Auto Access] Attacker: 31.14.115.42, Threshold: 1, Attempts: 1
2022-10-25 04:34:10.393 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 04:34:10.393 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 04:34:10.502 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 04:34:10.504 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 04:34:10.504 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.79
2022-10-25 04:34:10.570 - [Debug] [Connection] Attacker connected: 103.90.177.102 | Client Identification: SSH-2.0-Go
2022-10-25 04:34:10.644 - [Debug] [Connection] Attacker connected: 10.205.191.47 | Client Identification: SSH-2.0-OpenSSH_7.5
2022-10-25 04:34:11.711 - [Debug] [Auth] Attacker 223.171.91.158 trying to authenticate with 'none'
2022-10-25 04:34:11.711 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 04:34:12.207 - [Debug] [Auth] Attacker 223.171.91.158 trying to authenticate with 'publickey'
2022-10-25 04:34:12.208 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 04:34:12.209 - [Debug] [Auth] Attacker: 223.171.91.158 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 04:34:12.250 - [Debug] [Auth] Attacker 103.90.177.102 trying to authenticate with 'none'
2022-10-25 04:34:12.250 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 04:34:12.733 - [Debug] [Connection] Attacker closed the connection
2022-10-25 04:34:12.927 - [Debug] [Auth] Attacker 103.90.177.102 trying to authenticate with 'publickey'
2022-10-25 04:34:12.928 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 04:34:12.928 - [Debug] [Auth] Attacker: 103.90.177.102 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 04:34:13.017 - [Debug] [Connection] Attacker connected: 223.171.91.158 | Client Identification: SSH-2.0-Go
2022-10-25 04:34:13.067 - [Debug] [Auth] Attacker 10.205.191.47 trying to authenticate with 'none'
2022-10-25 04:34:13.068 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 04:34:13.551 - [Debug] [Connection] Attacker closed the connection
