
2022-10-25 02:23:02.971 - [Debug] [Auth] Attacker 93.91.117.60 trying to authenticate with 'publickey'
2022-10-25 02:23:02.973 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 02:23:02.973 - [Debug] [Auth] Attacker: 93.91.117.60 has so far made 1 attempts. Remaining: 5 attempts
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:2907321) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_4',
  containerIp: '10.0.3.18',
  mitmPort: 1003,
  autoAccessFixed: 1
}
2022-10-25 02:24:08.041 - [Info] MITM Version: 2
2022-10-25 02:24:08.042 - [Info] Auto Access Enabled: true
2022-10-25 02:24:08.042 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 02:24:08.049 - [Info] SSH man-in-the-middle server for 10.0.3.18 listening on 10.0.3.1:1003
2022-10-25 02:24:08.392 - [Debug] [Connection] Attacker connected: 223.99.166.104 | Client Identification: SSH-2.0-Go
2022-10-25 02:24:08.588 - [Debug] [Connection] Attacker connected: 157.245.137.18 | Client Identification: SSH-2.0-Go
2022-10-25 02:24:08.699 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'none'
2022-10-25 02:24:08.699 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 02:24:08.763 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'password'
2022-10-25 02:24:08.764 - [Debug] [Auto Access] Attacker: 157.245.137.18, Threshold: 1, Attempts: 1
2022-10-25 02:24:08.764 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 02:24:08.764 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 02:24:08.820 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 02:24:08.822 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 02:24:08.822 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.18
2022-10-25 02:24:08.827 - [Debug] [Connection] Attacker connected: 222.134.240.91 | Client Identification: SSH-2.0-Go
2022-10-25 02:24:08.877 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-25 02:24:08.901 - [Debug] [Connection] Attacker connected: 89.212.123.191 | Client Identification: SSH-2.0-Go
2022-10-25 02:24:09.003 - [Debug] [EXEC] Noninteractive mode attacker command: uname -a
2022-10-25 02:24:09.070 - [Debug] [Connection] Attacker closed connection
2022-10-25 02:24:09.076 - [Debug] [LXC] Container's OpenSSH server ended connection
2022-10-25 02:24:09.077 - [Debug] [LXC] Container's OpenSSH server closed connection
