
(node:1011742) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.182',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:37:56.247 - [Info] MITM Version: 2
2022-10-25 19:37:56.248 - [Info] Auto Access Enabled: true
2022-10-25 19:37:56.249 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:37:56.259 - [Info] SSH man-in-the-middle server for 10.0.3.182 listening on 10.0.3.1:1000
2022-10-25 19:38:28.822 - [Debug] [Connection] Attacker connected: 157.245.137.18 | Client Identification: SSH-2.0-Go
(node:1014342) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.99',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:38:29.275 - [Info] MITM Version: 2
2022-10-25 19:38:29.277 - [Info] Auto Access Enabled: true
2022-10-25 19:38:29.277 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:38:29.275 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'none'
2022-10-25 19:38:29.283 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:38:29.338 - [Debug] listen EADDRINUSE: address already in use 10.0.3.1:1000
2022-10-25 19:38:29.340 - [Error] Another MITM instance or another program is already listening on this port
{"level":"error","message":"Forever detected script exited with code: 1"}
2022-10-25 19:38:29.443 - [Debug] [Auth] Attacker 157.245.137.18 trying to authenticate with 'password'
2022-10-25 19:38:29.444 - [Debug] [Auto Access] Attacker: 157.245.137.18, Threshold: 1, Attempts: 1
2022-10-25 19:38:29.444 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 19:38:29.444 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 19:38:29.797 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 19:38:29.800 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 19:38:29.800 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.182
2022-10-25 19:38:31.574 - [Debug] [Connection] Attacker connected: 89.121.228.38 | Client Identification: SSH-2.0-Go
2022-10-25 19:38:32.432 - [Debug] [Auth] Attacker 89.121.228.38 trying to authenticate with 'none'
2022-10-25 19:38:32.432 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:38:32.471 - [Debug] [Connection] Attacker connected: 95.91.13.119 | Client Identification: SSH-2.0-Go
2022-10-25 19:38:32.744 - [Debug] [Auth] Attacker 89.121.228.38 trying to authenticate with 'publickey'
2022-10-25 19:38:32.746 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:38:32.747 - [Debug] [Auth] Attacker: 89.121.228.38 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 19:38:33.057 - [Debug] [Connection] Attacker closed the connection
