
(node:1098275) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.71',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:47:20.964 - [Info] MITM Version: 2
2022-10-25 19:47:20.965 - [Info] Auto Access Enabled: true
2022-10-25 19:47:20.966 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:47:20.985 - [Info] SSH man-in-the-middle server for 10.0.3.71 listening on 10.0.3.1:1000
2022-10-25 19:47:53.062 - [Debug] [Connection] Attacker connected: 62.12.108.44 | Client Identification: SSH-2.0-Go
(node:1107199) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.188',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:47:53.452 - [Info] MITM Version: 2
2022-10-25 19:47:53.454 - [Info] Auto Access Enabled: true
2022-10-25 19:47:53.455 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:47:53.484 - [Debug] listen EADDRINUSE: address already in use 10.0.3.1:1000
2022-10-25 19:47:53.490 - [Error] Another MITM instance or another program is already listening on this port
{"level":"error","message":"Forever detected script exited with code: 1"}
2022-10-25 19:47:54.034 - [Debug] [Auth] Attacker 62.12.108.44 trying to authenticate with 'none'
2022-10-25 19:47:54.035 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:47:54.382 - [Debug] [Auth] Attacker 62.12.108.44 trying to authenticate with 'password'
2022-10-25 19:47:54.383 - [Debug] [Auto Access] Attacker: 62.12.108.44, Threshold: 1, Attempts: 1
2022-10-25 19:47:54.383 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 19:47:54.383 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 19:47:54.475 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 19:47:54.477 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 19:47:54.477 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.71
2022-10-25 19:47:55.111 - [Debug] [Connection] Attacker connected: 144.22.191.115 | Client Identification: SSH-2.0-Go
2022-10-25 19:47:55.900 - [Debug] [Auth] Attacker 144.22.191.115 trying to authenticate with 'none'
2022-10-25 19:47:55.900 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:47:56.149 - [Debug] [Auth] Attacker 144.22.191.115 trying to authenticate with 'publickey'
2022-10-25 19:47:56.150 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:47:56.152 - [Debug] [Auth] Attacker: 144.22.191.115 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 19:47:56.401 - [Debug] [Connection] Attacker closed the connection
2022-10-25 19:47:56.525 - [Debug] [Connection] Attacker connected: 144.22.191.115 | Client Identification: SSH-2.0-Go
