
2022-10-25 18:59:50.502 - [Debug] [Connection] Attacker connected: 119.4.109.85 | Client Identification: SSH-2.0-Go
2022-10-25 18:59:50.503 - [Debug] [Auth] Attacker 20.127.87.36 trying to authenticate with 'none'
2022-10-25 18:59:50.504 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 18:59:50.505 - [Debug] [Connection] Attacker connected: 184.67.149.186 | Client Identification: SSH-2.0-Go
2022-10-25 18:59:50.529 - [Debug] [Auth] Attacker 20.127.87.36 trying to authenticate with 'password'
2022-10-25 18:59:50.529 - [Debug] [Auto Access] Attacker: 20.127.87.36, Threshold: 1, Attempts: 1
2022-10-25 18:59:50.530 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 18:59:50.530 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 18:59:50.606 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 18:59:50.608 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 18:59:50.608 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.242
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:652370) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_1',
  containerIp: '10.0.3.233',
  mitmPort: 1000,
  autoAccessFixed: 1
}
2022-10-25 19:00:24.523 - [Info] MITM Version: 2
2022-10-25 19:00:24.525 - [Info] Auto Access Enabled: true
2022-10-25 19:00:24.526 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:00:24.540 - [Info] SSH man-in-the-middle server for 10.0.3.233 listening on 10.0.3.1:1000
2022-10-25 19:00:26.736 - [Debug] [Connection] Attacker connected: 118.218.209.149 | Client Identification: SSH-2.0-Go
2022-10-25 19:00:26.875 - [Debug] [Connection] Attacker connected: 222.165.136.99 | Client Identification: SSH-2.0-Go
2022-10-25 19:00:27.350 - [Debug] [Connection] Attacker connected: 59.3.186.45 | Client Identification: SSH-2.0-Go
2022-10-25 19:00:28.074 - [Debug] [Auth] Attacker 118.218.209.149 trying to authenticate with 'none'
2022-10-25 19:00:28.074 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:00:28.321 - [Debug] [Auth] Attacker 222.165.136.99 trying to authenticate with 'none'
2022-10-25 19:00:28.321 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:00:28.546 - [Debug] [Auth] Attacker 118.218.209.149 trying to authenticate with 'publickey'
2022-10-25 19:00:28.547 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:00:28.548 - [Debug] [Auth] Attacker: 118.218.209.149 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 19:00:28.632 - [Debug] [Auth] Attacker 59.3.186.45 trying to authenticate with 'none'
2022-10-25 19:00:28.632 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:00:28.830 - [Debug] [Auth] Attacker 222.165.136.99 trying to authenticate with 'password'
2022-10-25 19:00:28.831 - [Debug] [Auto Access] Attacker: 222.165.136.99, Threshold: 1, Attempts: 1
2022-10-25 19:00:28.831 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 19:00:28.831 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 19:00:28.884 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 19:00:28.886 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 19:00:28.886 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.233
2022-10-25 19:00:28.929 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-25 19:00:29.007 - [Debug] [Connection] Attacker closed the connection
2022-10-25 19:00:29.071 - [Debug] [Auth] Attacker 59.3.186.45 trying to authenticate with 'publickey'
2022-10-25 19:00:29.072 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:00:29.072 - [Debug] [Auth] Attacker: 59.3.186.45 has so far made 1 attempts. Remaining: 5 attempts
