
2022-10-25 18:40:59.634 - [Debug] [Auth] Attacker 209.216.177.158 trying to authenticate with 'none'
2022-10-25 18:40:59.635 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 18:40:59.654 - [Debug] [Auth] Attacker 14.152.78.120 trying to authenticate with 'none'
2022-10-25 18:40:59.654 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 18:40:59.779 - [Debug] [Connection] Attacker connected: 219.140.162.82 | Client Identification: SSH-2.0-Go
2022-10-25 18:40:59.842 - [Debug] [Auth] Attacker 209.216.177.158 trying to authenticate with 'password'
2022-10-25 18:40:59.843 - [Debug] [Auto Access] Attacker: 209.216.177.158, Threshold: 1, Attempts: 1
2022-10-25 18:40:59.843 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 18:40:59.843 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 18:41:00.217 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 18:41:00.219 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 18:41:00.219 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.53
2022-10-25 18:41:00.239 - [Debug] [Auth] Attacker 14.152.78.120 trying to authenticate with 'publickey'
2022-10-25 18:41:00.240 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 18:41:00.241 - [Debug] [Auth] Attacker: 14.152.78.120 has so far made 1 attempts. Remaining: 5 attempts
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:513967) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_3',
  containerIp: '10.0.3.110',
  mitmPort: 1002,
  autoAccessFixed: 1
}
2022-10-25 18:41:46.056 - [Info] MITM Version: 2
2022-10-25 18:41:46.057 - [Info] Auto Access Enabled: true
2022-10-25 18:41:46.057 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 18:41:46.072 - [Info] SSH man-in-the-middle server for 10.0.3.110 listening on 10.0.3.1:1002
2022-10-25 18:41:46.273 - [Debug] [Connection] Attacker connected: 112.160.137.62 | Client Identification: SSH-2.0-Go
2022-10-25 18:41:46.717 - [Debug] [Connection] Attacker connected: 85.51.217.156 | Client Identification: SSH-2.0-Go
2022-10-25 18:41:47.222 - [Debug] [Connection] Attacker connected: 118.218.209.149 | Client Identification: SSH-2.0-Go
2022-10-25 18:41:47.499 - [Debug] [Auth] Attacker 85.51.217.156 trying to authenticate with 'none'
2022-10-25 18:41:47.500 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 18:41:47.535 - [Debug] [Auth] Attacker 112.160.137.62 trying to authenticate with 'none'
2022-10-25 18:41:47.536 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 18:41:47.822 - [Debug] [Auth] Attacker 85.51.217.156 trying to authenticate with 'publickey'
2022-10-25 18:41:47.824 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 18:41:47.825 - [Debug] [Auth] Attacker: 85.51.217.156 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 18:41:47.973 - [Debug] [Auth] Attacker 112.160.137.62 trying to authenticate with 'publickey'
2022-10-25 18:41:47.974 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 18:41:47.974 - [Debug] [Auth] Attacker: 112.160.137.62 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 18:41:48.096 - [Debug] [Connection] Attacker closed the connection
