
2022-10-25 00:27:31.115 - [Debug] [Auth] Attacker 31.14.115.42 trying to authenticate with 'none'
2022-10-25 00:27:31.115 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:27:31.194 - [Debug] [Auth] Attacker 120.197.154.22 trying to authenticate with 'none'
2022-10-25 00:27:31.194 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:27:31.247 - [Debug] [Auth] Attacker 89.100.220.200 trying to authenticate with 'none'
2022-10-25 00:27:31.247 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:27:31.360 - [Debug] [Auth] Attacker 5.28.139.161 trying to authenticate with 'none'
2022-10-25 00:27:31.360 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:27:31.436 - [Debug] [Connection] Attacker connected: 89.212.123.191 | Client Identification: SSH-2.0-Go
2022-10-25 00:27:31.480 - [Debug] [Auth] Attacker 89.100.220.200 trying to authenticate with 'password'
2022-10-25 00:27:31.481 - [Debug] [Auto Access] Attacker: 89.100.220.200, Threshold: 1, Attempts: 1
2022-10-25 00:27:31.481 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 00:27:31.481 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 00:27:31.545 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 00:27:31.547 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 00:27:31.547 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.116
2022-10-25 00:27:31.604 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:1831365) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_4',
  containerIp: '10.0.3.117',
  mitmPort: 1003,
  autoAccessFixed: 1
}
2022-10-25 00:28:50.860 - [Info] MITM Version: 2
2022-10-25 00:28:50.861 - [Info] Auto Access Enabled: true
2022-10-25 00:28:50.863 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 00:28:50.880 - [Info] SSH man-in-the-middle server for 10.0.3.117 listening on 10.0.3.1:1003
2022-10-25 00:28:51.702 - [Debug] [Connection] Attacker connected: 147.182.233.56 | Client Identification: SSH-2.0-Go
2022-10-25 00:28:52.012 - [Debug] [Connection] Attacker connected: 223.171.91.120 | Client Identification: SSH-2.0-Go
2022-10-25 00:28:52.181 - [Debug] [Auth] Attacker 147.182.233.56 trying to authenticate with 'none'
2022-10-25 00:28:52.182 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:28:52.327 - [Debug] [Auth] Attacker 147.182.233.56 trying to authenticate with 'publickey'
2022-10-25 00:28:52.330 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 00:28:52.330 - [Debug] [Auth] Attacker: 147.182.233.56 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 00:28:52.462 - [Debug] [Connection] Attacker connected: 139.59.135.142 | Client Identification: SSH-2.0-Go
2022-10-25 00:28:52.485 - [Debug] [Connection] Attacker closed the connection
2022-10-25 00:28:52.550 - [Debug] [Connection] Attacker connected: 147.182.233.56 | Client Identification: SSH-2.0-Go
2022-10-25 00:28:53.027 - [Debug] [Auth] Attacker 147.182.233.56 trying to authenticate with 'none'
2022-10-25 00:28:53.027 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 00:28:53.080 - [Debug] [Auth] Attacker 139.59.135.142 trying to authenticate with 'none'
2022-10-25 00:28:53.080 - [Debug] [Auth] Attacker authentication error: No authentication method provided
