
(node:843574) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_2',
  containerIp: '10.0.3.238',
  mitmPort: 1001,
  autoAccessFixed: 1
}
2022-10-25 19:20:14.265 - [Info] MITM Version: 2
2022-10-25 19:20:14.267 - [Info] Auto Access Enabled: true
2022-10-25 19:20:14.268 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:20:14.280 - [Info] SSH man-in-the-middle server for 10.0.3.238 listening on 10.0.3.1:1001
2022-10-25 19:21:27.816 - [Debug] [Connection] Attacker connected: 184.67.149.186 | Client Identification: SSH-2.0-Go
2022-10-25 19:21:28.017 - [Debug] [Connection] Attacker connected: 209.216.177.158 | Client Identification: SSH-2.0-Go
(node:855512) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_2',
  containerIp: '10.0.3.18',
  mitmPort: 1001,
  autoAccessFixed: 1
}
2022-10-25 19:21:28.228 - [Info] MITM Version: 2
2022-10-25 19:21:28.229 - [Info] Auto Access Enabled: true
2022-10-25 19:21:28.230 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 19:21:28.241 - [Debug] listen EADDRINUSE: address already in use 10.0.3.1:1001
2022-10-25 19:21:28.241 - [Error] Another MITM instance or another program is already listening on this port
{"level":"error","message":"Forever detected script exited with code: 1"}
2022-10-25 19:21:28.369 - [Debug] [Auth] Attacker 184.67.149.186 trying to authenticate with 'none'
2022-10-25 19:21:28.369 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:21:28.581 - [Debug] [Auth] Attacker 209.216.177.158 trying to authenticate with 'none'
2022-10-25 19:21:28.581 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 19:21:28.592 - [Debug] [Auth] Attacker 184.67.149.186 trying to authenticate with 'password'
2022-10-25 19:21:28.593 - [Debug] [Auto Access] Attacker: 184.67.149.186, Threshold: 1, Attempts: 1
2022-10-25 19:21:28.594 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 19:21:28.594 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 19:21:28.712 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 19:21:28.714 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 19:21:28.714 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.238
2022-10-25 19:21:28.790 - [Debug] [Auth] Attacker 209.216.177.158 trying to authenticate with 'publickey'
2022-10-25 19:21:28.791 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 19:21:28.792 - [Debug] [Auth] Attacker: 209.216.177.158 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 19:21:29.002 - [Debug] [Connection] Attacker closed the connection
2022-10-25 19:21:29.088 - [Debug] [Connection] Attacker connected: 209.216.177.158 | Client Identification: SSH-2.0-Go
