
(node:157308) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'DATABASE_4',
  containerIp: '10.0.3.42',
  mitmPort: 1003,
  autoAccessFixed: 1
}
2022-10-25 04:32:28.032 - [Info] MITM Version: 2
2022-10-25 04:32:28.033 - [Info] Auto Access Enabled: true
2022-10-25 04:32:28.033 - [Debug] [Init] Auto Access Theshold Achieved: false
2022-10-25 04:32:28.040 - [Info] SSH man-in-the-middle server for 10.0.3.42 listening on 10.0.3.1:1003
2022-10-25 04:32:28.419 - [Debug] [Connection] Attacker connected: 223.171.91.148 | Client Identification: SSH-2.0-Go
2022-10-25 04:32:28.427 - [Debug] [Connection] Attacker connected: 89.121.228.38 | Client Identification: SSH-2.0-Go
2022-10-25 04:32:29.257 - [Debug] [Auth] Attacker 89.121.228.38 trying to authenticate with 'none'
2022-10-25 04:32:29.257 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 04:32:29.555 - [Debug] [Auth] Attacker 89.121.228.38 trying to authenticate with 'publickey'
2022-10-25 04:32:29.556 - [Debug] [Auth] Attacker authentication error: Publickey authentication failed
2022-10-25 04:32:29.557 - [Debug] [Auth] Attacker: 89.121.228.38 has so far made 1 attempts. Remaining: 5 attempts
2022-10-25 04:32:29.844 - [Debug] [Auth] Attacker 223.171.91.148 trying to authenticate with 'none'
2022-10-25 04:32:29.844 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2022-10-25 04:32:29.862 - [Debug] [Connection] Attacker closed the connection
2022-10-25 04:32:30.336 - [Debug] [Auth] Attacker 223.171.91.148 trying to authenticate with 'password'
2022-10-25 04:32:30.336 - [Debug] [Auto Access] Attacker: 223.171.91.148, Threshold: 1, Attempts: 1
2022-10-25 04:32:30.336 - [Debug] [Auto Access] Compromising the honeypot
2022-10-25 04:32:30.336 - [Debug] [Auto Access] Adding the following credentials: 'root:1'
2022-10-25 04:32:30.603 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2022-10-25 04:32:30.605 - [Debug] [Auth] Valid credentials - Password Authentication
2022-10-25 04:32:30.605 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.42
2022-10-25 04:32:30.617 - [Debug] [Connection] Attacker connected: 222.134.240.92 | Client Identification: SSH-2.0-Go
2022-10-25 04:32:30.657 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2022-10-25 04:32:30.988 - [Debug] [Connection] Attacker connected: 89.121.228.38 | Client Identification: SSH-2.0-Go
